language: python
python:
  - "3.8"
install:
    - pip install python-coveralls
    - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python - --preview
    - PATH="${PATH}:$HOME/.poetry/bin"
    - poetry config virtualenvs.create false && poetry install --no-interaction --no-ansi
    - pip install git+https://github.com/lundberg/respx.git@dev --upgrade
    - pip install git+https://github.com/encode/httpx.git --upgrade
script:
    - pytest -v tests/
after_success:
  - coveralls
